openapi: 3.0.0
info:
  title: URL Link Shortener API
  description: API for managing short URLs and user accounts.
  version: "1.0.0"
  contact:
    name: "API Support"
    url: "https://cs3103.cs.unb.ca/hhong/project/support"
    email: "leo.hong@unb.ca"
servers:
  - url: "https://cs3103.cs.unb.ca/hhong/project/api"
paths:
  /users/login:
    post:
      summary: Authenticates a user via LDAP and checks/adds them in the local database
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginCredentials"
      responses:
        "200":
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        "401":
          description: Authentication failed. Invalid username or password.
        "500":
          description: Internal server error, e.g., LDAP server is not reachable.
/users/logout:
  post:
    summary: Logs out a user
    tags:
      - Users
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/LogoutRequest"
    responses:
      "200":
        description: Logout successful
      "401":
        description: Not logged in
      "500":
        description: Internal server error  
  /users/{userId}/links:
    get:
      summary: Retrieves all links created by a specific user
      tags:
        - Links
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Link"
        "404":
          description: User not found
  /links:
    post:
      summary: Creates a new short link
      tags:
        - Links
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewLinkRequest"
      responses:
        "201":
          description: Link created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Link"
        "400":
          description: Invalid input
  /links/{linkId}:
    delete:
      summary: Deletes a specific link
      tags:
        - Links
      parameters:
        - in: path
          name: linkId
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Link deleted successfully
        "404":
          description: Link not found
        "403":
          description: User not authorized to delete this link
  /links/shortcut/{shortcut}:
    get:
      summary: Retrieves the original URL by shortcut
      tags:
        - Links
      parameters:
        - in: path
          name: shortcut
          required: true
          schema:
            type: string
      responses:
        "302":
          description: Redirect to the destination URL
          headers:
            Location:
              schema:
                type: string
                format: uri
                description: URL to redirect to
        "404":
          description: Shortcut not found
components:
  schemas:
    UserCreatedResponse:
      type: object
      properties:
        username:
          type: string
      required:
        - username
    LoginCredentials:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password 
    LogoutRequest:
      type: object
      properties:
        userId:
          type: integer
      required:
        - userId
    AuthResponse:
      type: object
      properties:
        userId:
          type: integer
          description: The local user ID assigned to the LDAP user.
        username:
          type: string
          description: The username of the authenticated user.
      required:
        - userId
        - username
    NewLinkRequest:
      type: object
      properties:
        destination:
          type: string
          format: uri
        userId:
          type: integer
          nullable: true
      required:
        - destination
    Link:
      type: object
      properties:
        linkId:
          type: integer
        destination:
          type: string
        shortcut:
          type: string
        userId:
          type: integer
          nullable: true
      required:
        - linkId
        - destination
        - shortcut
